### ISSUE TITLE
Spostiamo gli Enum in una classe dedicata

### ISSUE THREAD

**Issue by emmathebear** [develhope/Java23-Team1-Dealer#10]
https://github.com/develhope/Java23-Team1-Dealer/blob/6fa4d2997e16c16aacf8c4fc3df13685dd7bf6ea/src/main/java/com/develhope/spring/vehicles/entity/Vehicles.java#L7

**Comment by hatefulTtamer** [comment]
https://github.com/develhope/Java23-Team1-Dealer/pull/14
